import type { CallLog, Patient, Reminder } from "./types";

export const demoPatients: Patient[] = [
  {
    id: "patient-mary-thompson",
    name: "Mary Thompson",
    age: 78,
    phone: "+1 (416) 555-0198",
    relationship: "Mother",
    notes: "Early-stage dementia, needs medication reminders",
    riskLevel: "Medium",
    preferredTone: "Family-like",
    createdAt: "2026-05-26T18:00:00.000Z",
  },
  {
    id: "patient-john-rivera",
    name: "John Rivera",
    age: 83,
    phone: "+1 (416) 555-0142",
    relationship: "Father",
    notes: "Needs gentle meal and hydration reminders. Escalate confusion.",
    riskLevel: "High",
    preferredTone: "Calm assistant",
    createdAt: "2026-05-26T18:05:00.000Z",
  },
];

export const demoReminders: Reminder[] = [
  {
    id: "reminder-evening-medication",
    patientId: "patient-mary-thompson",
    patientName: "Mary Thompson",
    type: "Medication",
    title: "Evening medication",
    message:
      "Hi Mary, this is your reminder to take your evening blood pressure medication.",
    scheduledDate: "Today",
    scheduledTime: "7:00 PM",
    repeat: "Daily",
    voiceStyle: "Family-like",
    safetyAlert: true,
    status: "Completed",
    summary: "Mary confirmed she took her medication.",
    createdAt: "2026-05-26T18:10:00.000Z",
  },
  {
    id: "reminder-lunch",
    patientId: "patient-mary-thompson",
    patientName: "Mary Thompson",
    type: "Meal",
    title: "Lunch reminder",
    message: "Hi Mary, it is time for lunch. Please check the kitchen table.",
    scheduledDate: "Today",
    scheduledTime: "12:30 PM",
    repeat: "Daily",
    voiceStyle: "Calm assistant",
    safetyAlert: true,
    status: "Completed",
    summary: "Mary said she was sitting down for lunch.",
    createdAt: "2026-05-26T16:15:00.000Z",
  },
  {
    id: "reminder-hydration",
    patientId: "patient-mary-thompson",
    patientName: "Mary Thompson",
    type: "Hydration",
    title: "Hydration check",
    message: "Hi Mary, please take a few sips of water if your glass is nearby.",
    scheduledDate: "Today",
    scheduledTime: "3:00 PM",
    repeat: "Daily",
    voiceStyle: "Gentle nurse",
    safetyAlert: true,
    status: "Needs Attention",
    summary: "Mary sounded unsure and asked where her water was.",
    createdAt: "2026-05-26T17:25:00.000Z",
  },
  {
    id: "reminder-doctor-appointment",
    patientId: "patient-mary-thompson",
    patientName: "Mary Thompson",
    type: "Appointment",
    title: "Doctor appointment",
    message:
      "Hi Mary, you have a doctor appointment tomorrow morning. Your caregiver will pick you up.",
    scheduledDate: "Tomorrow",
    scheduledTime: "10:00 AM",
    repeat: "Once",
    voiceStyle: "Calm assistant",
    safetyAlert: true,
    status: "Pending",
    createdAt: "2026-05-26T17:40:00.000Z",
  },
];

export const maryTranscript = [
  {
    speaker: "AI" as const,
    text: "Hi Mary, this is MemoryLine calling with your evening medication reminder.",
  },
  { speaker: "Patient" as const, text: "Oh, okay. Which one?" },
  {
    speaker: "AI" as const,
    text: "Your evening blood pressure medication. Please take it with water if it is nearby.",
  },
  { speaker: "Patient" as const, text: "Yes, I have it here." },
  { speaker: "AI" as const, text: "Great. Did you take it?" },
  { speaker: "Patient" as const, text: "Yes, I took it now." },
  {
    speaker: "AI" as const,
    text: "Thank you, Mary. I'll let your caregiver know.",
  },
];

export const demoCallLogs: CallLog[] = [
  {
    id: "log-evening-medication",
    reminderId: "reminder-evening-medication",
    patientId: "patient-mary-thompson",
    patientName: "Mary Thompson",
    reminderTitle: "Evening medication",
    dateTime: "Today, 7:02 PM",
    status: "Completed",
    summary: "Mary confirmed she took her medication after one reminder.",
    transcript: maryTranscript,
    caregiverAlert: "No urgent concerns detected.",
  },
  {
    id: "log-lunch",
    reminderId: "reminder-lunch",
    patientId: "patient-mary-thompson",
    patientName: "Mary Thompson",
    reminderTitle: "Lunch reminder",
    dateTime: "Today, 12:33 PM",
    status: "Completed",
    summary: "Mary said she was sitting down for lunch.",
    transcript: [
      {
        speaker: "AI",
        text: "Hi Mary, this is MemoryLine with your lunch reminder.",
      },
      { speaker: "Patient", text: "Lunch is on the table, yes." },
      {
        speaker: "AI",
        text: "That is great. I will let your caregiver know you are set.",
      },
    ],
    caregiverAlert: "No urgent concerns detected.",
  },
  {
    id: "log-hydration",
    reminderId: "reminder-hydration",
    patientId: "patient-mary-thompson",
    patientName: "Mary Thompson",
    reminderTitle: "Hydration check",
    dateTime: "Today, 3:03 PM",
    status: "Needs Attention",
    summary: "Mary sounded unsure and asked where her water was.",
    transcript: [
      {
        speaker: "AI",
        text: "Hi Mary, please take a few sips of water if your glass is nearby.",
      },
      { speaker: "Patient", text: "I do not know where it is." },
      {
        speaker: "AI",
        text: "That is okay. I will let your caregiver know you may need help.",
      },
    ],
    caregiverAlert: "Caregiver should check in when available.",
  },
  {
    id: "log-john-meal",
    reminderId: "reminder-john-meal",
    patientId: "patient-john-rivera",
    patientName: "John Rivera",
    reminderTitle: "Meal reminder",
    dateTime: "Today, 5:45 PM",
    status: "Confused",
    summary: "John seemed confused during the meal reminder.",
    transcript: [
      {
        speaker: "AI",
        text: "Hi John, this is your gentle reminder to check the prepared dinner.",
      },
      { speaker: "Patient", text: "Who is this? Did I already eat?" },
      {
        speaker: "AI",
        text: "This is MemoryLine. I will let your caregiver know you may need support.",
      },
    ],
    caregiverAlert: "Follow up recommended due to confusion.",
  },
  {
    id: "log-robert-no-answer",
    reminderId: "reminder-robert-safety",
    patientId: "patient-robert-chen",
    patientName: "Robert Chen",
    reminderTitle: "Safety check",
    dateTime: "Today, 9:10 AM",
    status: "No Answer",
    summary: "No answer after two call attempts.",
    transcript: [],
    caregiverAlert: "No urgent concerns detected, but consider checking in.",
  },
  {
    id: "log-mary-morning-check",
    reminderId: "reminder-mary-morning-check",
    patientId: "patient-mary-thompson",
    patientName: "Mary Thompson",
    reminderTitle: "Morning safety check",
    dateTime: "Today, 8:15 AM",
    status: "Completed",
    summary: "Mary said she felt well and had breakfast nearby.",
    transcript: [
      {
        speaker: "AI",
        text: "Good morning Mary, this is a gentle safety check.",
      },
      { speaker: "Patient", text: "I feel fine. Breakfast is here." },
      {
        speaker: "AI",
        text: "Thank you, Mary. I will share that update with your caregiver.",
      },
    ],
    caregiverAlert: "No urgent concerns detected.",
  },
];
